export const text =
    'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nesciunt veniam aspernaturmolestias quasi neque nihil excepturi dignissimos, facilis assumenda ex a idperferendis libero asperiores praesentium pariatur voluptatem esse est tempora. Estlaudantium qui, voluptates laboriosam placeat aspernatur vel ipsa quidem! Cumque fugaqui quae natus iste cupiditate deleniti suscipit!';

export const texts = [
    'number',
    'string',
    'function',
    'array',
    'object',
    'null',
    'return',
    'undefiend',
    'method',
    'get',
    'set',
    'literal',
    'expression',
    'operator',
    'operand',
    'for',
    'while',
    'length',
    'map',
    'each',
    'filter',
    'from',
    'import',
    'export',
    'const',
    'setTimeout',
    'setInterval',
    'promise',
    'async',
    'await',
    'reject',
    'resolve',
    'responce',
    'useState',
    'useCallback',
    'useEffect',
    'React',
    'default',
];
